spring.application.name=superior-email
spring.autoconfigure.exclude=org.springframework.boot.hibernate.autoconfigure.HibernateJpaAutoConfiguration,org.springframework.boot.jdbc.autoconfigure.DataSourceAutoConfiguration
spring.config.import=optional:application-local.properties

mail.imap.host=imap.gmail.com
mail.imap.port=993
